### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cdupont** [mvdan/hint#31] opened 2017-05-13 23:10 UTC
Hello,
I managed to create a seg fault using Hint:

```
import Control.Monad
import Language.Haskell.Interpreter
import SomeModule
import Data.Typeable

main :: IO ()
main = void $ runInterpreter $ do
   -- First version of Test.hs
   liftIO $ writeFile "Test.hs" "module Test where data T = T Int deriving (Show, Eq)"
   loadModules ["Test.hs", "SomeModule.hs"]
   setTopLevelModules ["Test", "SomeModule"]
   (L x) <- interpret "L (T 1)" (as :: L)
 
  -- Second version of Test.hs
   liftIO $ writeFile "Test.hs" "module Test where data T = T Int Int deriving (Show, Eq)"
   loadModules ["Test.hs", "SomeModule.hs"]
   setTopLevelModules ["Test", "SomeModule"]
   (L y) <- interpret "L (T 1 2)" (as :: L)

   -- combine the two   
   liftIO $ putStrLn $ show $ cast x == Just y
```

SomeModule is:
```
{-# LANGUAGE ExistentialQuantification #-}

module SomeModule where
import Data.Typeable

data L = forall a . (Typeable a, Eq a) => L a 
```

runhaskell main.hs gives:
```
Segmentation fault (core dumped)
```

As you can see, we interpret twice nearly the same code, but with different expectations for datatype `T`.
First time we have:
```
data T = T String
```
and second time we have:
```
data T = T String String
```

So when the runtime tries to combines the two, there is two different representations of the same type (same name). This makes read some wrong memory page and crashes.

**Comment by cdupont** [comment] 2017-05-13 23:14
It might not be a bug, or if it's a bug it might not be easy to correct :)
Anyway, my use case is for the game Nomyx.
This issue will allow a players to submit some rule that will crash the server: https://github.com/nomyx/Nomyx/issues/188

So the question is: is there anything I can do in my code to prevent the issue? i.e. How can I detect that the run-time representations does not match?
Thanks and cheers!

**Comment by gelisam** [comment] 2017-05-14 01:55
Interesting. So GHC is only using the fully-qualified name to distinguish whether the Typeable instances are equal? This isn't true with the PackageImports extension for example, and I remember that GHC added a more sophisticated fingerprinting implementation when it decided to allow multiple versions of the same package as well. I'm guessing that this fancier fingerprinting isn't used in interpreted mode, and that it doesn't affect ghci because attempting to reload a new version of the same file clears the local variables?

**Comment by mvdan** [comment] 2017-05-14 10:42
What GHC version is this? Have you tried a recent version?

Is it the same segfaul when you use `runghc` and when you build a binary and then run that? (I've had `hint` segfault in one, but not the other)

**Comment by mvdan** [comment] 2017-05-14 10:44
Reproduced on Linux 4.10 amd64:

```
 $ runghc main.hs
Segmentation fault (core dumped)
 $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
```

**Comment by mvdan** [comment] 2017-05-14 10:48
If I use a binary instead - `ghc main.hs && ./main` - it doesn't segfault, but it doesn't print anything either.

Adding prints, it seems like it doesn't get past the first `setTopLevelModules` line. But using `runghc`, it does all debug prints until it segfaults at the very last line.

This is what I meant by `runghc` versus a binary - I have yet to figure out why `hint` behaves so differently in the two. Maybe it's how GHC is linked/used.

**Comment by mvdan** [comment] 2017-05-14 10:54
Here's another thought - I'm not confident that you can mix data obtained from the interpreter before and after a reset. `loadModules` does a `reset` so all imported modules are cleared and all loaded ones are unloaded.

I'm actually not sure, but it's entirely possible that using `x` in the last line is what is causing the breakage.

**Comment by gelisam** [comment] 2017-05-14 12:56
> This is what I meant by runghc versus a binary - I have yet to figure out why hint behaves so differently in the two. Maybe it's how GHC is linked/used.

runghc runs the code in interpreted mode, same as in ghci. My understanding is that the runtime representation of interpreted functions and the values they create is different from their compiled counterparts, and that there is some logic somewhere to convert between the two. Since hint runs code in interpreted mode, this conversion has to happen when hint returns values to the host program and that program is compiled, but not when that program also runs in interpreted mode.

**Comment by cdupont** [comment] 2017-05-14 20:55
Here is a cleaner version:
```
import Language.Haskell.Interpreter
import SomeModule
import Data.Typeable

main :: IO ()
main = do
  r <- runInterpreter $ do
    (L x) <- inter "module Test where import SomeModule; data T = T Int     deriving (Show, Eq)" "L (T 1)"
    (L y) <- inter "module Test where import SomeModule; data T = T Int Int deriving (Show, Eq)" "L (T 1 2)"
    liftIO $ putStrLn $ show $ cast x == Just y
  putStrLn $ show r

inter :: String -> String -> Interpreter L
inter mod s = do
   liftIO $ writeFile "Test.hs" mod
   loadModules ["Test.hs", "SomeModule.hs"]
   setTopLevelModules ["Test", "SomeModule"]
   interpret s (as :: L)
```

Note that if you swap x and y in the equality, there is no seg fault.
IMO the cast tricks GHC into thinking that there is `T Int Int` in memory, whereas there is only `T Int`. So to check for equality it will read some forbidden memory and segfault.
If you reverse the two, GHC will think there is `T Int` in memory, whereas there is `T Int Int`. Reading less than necessary is not harmful.

**Comment by cdupont** [comment] 2017-05-14 21:24
The problem is similar to the warning given on this function: https://github.com/mvdan/hint/blob/master/src/Hint/Context.hs#L180
Except here the mismatch is not between compiled code and interpreted code, but between two interpreted code.
@mvdan I think it's possible to mix code before and after reset, actually in [Nomyx](www.nomyx.net) we do that all the time: all rules are interpreted in separate hint sessions. Rules can talk to each other, it works well unless two rules define types with same name but different representations...

**Comment by cdupont** [comment] 2017-05-14 21:31
See also this bug in GHC: https://ghc.haskell.org/trac/ghc/ticket/7897

**Comment by gelisam** [comment] 2017-05-15 01:55
Aha, then that's the true cause of the bug: the TypeRep of the first and second `Test.T` should not be considered equal, but due to that bug you linked, they are considered equal.

It looks like the TypeRep representation has changed quite a bit since that bug was filed, there are no Strings in there anymore. And while TypeRep's Eq instance still considers two Types equal if they are nominally equal (only the first field, the "fingerprint" [is compared](https://hackage.haskell.org/package/base-4.9.1.0/docs/src/Data.Typeable.Internal.html#line-183), and that fingerprint is computed using [the package name, the module name, and the type name](https://hackage.haskell.org/package/base-4.9.1.0/docs/src/Data.Typeable.Internal.html#line-139)), it is possible to inspect the internals of TypeRep and to make our own decision:

    {-# LANGUAGE BangPatterns, MagicHash #-}

    import Language.Haskell.Interpreter
    import SomeModule
    import Data.Typeable as T
    import Data.Typeable.Internal
    import GHC.Ptr
    import GHC.Types
    import Text.Printf

    -- |
    -- >>> main
    -- t1 == t2: True
    -- t3 == t4: True
    -- t1 == t3: True
    -- tyCon1 == tyCon2: True
    -- tyCon3 == tyCon4: True
    -- tyCon1 == tyCon3: True
    -- aA1 == aA2: True
    -- aA3 == aA4: True
    -- aA1 == aA3: False
    -- Right ()
    main :: IO ()
    main = do
      r <- runInterpreter $ do
        (L x1, L x2) <- inter "module Test where\nimport SomeModule\ndata T = T Int     deriving (Show, Eq)" "(L (T 1), L (T 2))"
        (L x3, L x4) <- inter "module Test where\nimport SomeModule\ndata T = T Int Int deriving (Show, Eq)" "(L (T 1 2), L (T 3 4))"
        let t1 = T.typeOf x1
        let t2 = T.typeOf x2
        let t3 = T.typeOf x3
        let t4 = T.typeOf x4
        liftIO $ printf "t1 == t2: %s\n" $ show $ t1 == t2
        liftIO $ printf "t3 == t4: %s\n" $ show $ t3 == t4
        liftIO $ printf "t1 == t3: %s\n" $ show $ t1 == t3
        let TypeRep _ tyCon1 [] [] = t1
        let TypeRep _ tyCon2 [] [] = t2
        let TypeRep _ tyCon3 [] [] = t3
        let TypeRep _ tyCon4 [] [] = t4
        liftIO $ printf "tyCon1 == tyCon2: %s\n" $ show $ tyCon1 == tyCon2
        liftIO $ printf "tyCon3 == tyCon4: %s\n" $ show $ tyCon3 == tyCon4
        liftIO $ printf "tyCon1 == tyCon3: %s\n" $ show $ tyCon1 == tyCon3
        let TyCon _ _ m1 _ = tyCon1
        let TyCon _ _ m2 _ = tyCon2
        let TyCon _ _ m3 _ = tyCon3
        let TyCon _ _ m4 _ = tyCon4
        let Module mA1 _ = m1
        let Module mA2 _ = m2
        let Module mA3 _ = m3
        let Module mA4 _ = m4
        let aA1 = let !(TrNameS aA1') = mA1 in Ptr aA1'
        let aA2 = let !(TrNameS aA2') = mA2 in Ptr aA2'
        let aA3 = let !(TrNameS aA3') = mA3 in Ptr aA3'
        let aA4 = let !(TrNameS aA4') = mA4 in Ptr aA4'
        liftIO $ printf "aA1 == aA2: %s\n" $ show $ aA1 == aA2
        liftIO $ printf "aA3 == aA4: %s\n" $ show $ aA3 == aA4
        liftIO $ printf "aA1 == aA3: %s\n" $ show $ aA1 == aA3
      putStrLn $ show r

    inter :: String -> String -> Interpreter (L, L)
    inter mod_ s = do
       liftIO $ writeFile "Test.hs" mod_
       loadModules ["Test.hs", "SomeModule.hs"]
       setTopLevelModules ["Test", "SomeModule"]
       interpret s (as :: (L, L))

Here, loading `Test.hs` a second time causes a distinct Module object to be created. Pattern-matching deep into the TypeRep, we can obtain this Module, and even though there's no Eq instance for it, we can look at its `Addr#` fields and determine for ourselves whether they're the same. I have modified the example to return two `L`s in order to show that the two `L`s which come from the same module indeed have the same Module, while the `L`s which come from two different versions of `Test.hs` don't.

**Comment by gelisam** [comment] 2017-05-15 02:27
Having written all this, I now realize that this is not at all what you want for Nomyx. You don't want something even stricter than nominal equality, you want structural equality! Fortunately, this is even easier.

    {-# LANGUAGE BangPatterns, MagicHash, ScopedTypeVariables, TypeApplications #-}

    import Language.Haskell.Interpreter
    import Language.Haskell.Interpreter.Unsafe
    import SomeModule
    import Data.Proxy
    import Generics.Eot
    import Text.Printf

    -- |
    -- >>> main
    -- d1 == d2: False
    -- d1 == d3: True
    -- Right ()
    main :: IO ()
    main = do
      r <- unsafeRunInterpreterWithArgs ["-package-db=.cabal-sandbox/x86_64-osx-ghc-8.0.1-packages.conf.d/"] $ do
        L d1 _ <- inter "{-# LANGUAGE DeriveGeneric #-}\nmodule Test where\nimport GHC.Generics\nimport SomeModule\ndata T = T Int     deriving (Show, Eq, Generic)" "mkL (T 1)"
        L d2 _ <- inter "{-# LANGUAGE DeriveGeneric #-}\nmodule Test where\nimport GHC.Generics\nimport SomeModule\ndata T = T Int Int deriving (Show, Eq, Generic)" "mkL (T 2 3)"
        L d3 _ <- inter "{-# LANGUAGE DeriveGeneric #-}\nmodule Test where\nimport GHC.Generics\nimport SomeModule\ndata T = T Int     deriving (Show, Eq, Generic)" "mkL (T 4)"
        liftIO $ printf "d1 == d2: %s\n" $ show $ d1 == d2
        liftIO $ printf "d1 == d3: %s\n" $ show $ d1 == d3
      putStrLn $ show r

    eotDatatype :: forall a. HasEot a => a -> Datatype
    eotDatatype _ = datatype (Proxy @a)

    inter :: String -> String -> Interpreter L
    inter mod_ s = do
       liftIO $ writeFile "Test.hs" mod_
       loadModules ["Test.hs", "SomeModule.hs"]
       setTopLevelModules ["Test", "SomeModule"]
       interpret s (as :: L)

`SomeModule.hs`:

    {-# LANGUAGE ExistentialQuantification, ScopedTypeVariables, TypeApplications #-}
    
    module SomeModule where
    import Data.Proxy
    import GHC.Generics
    import qualified Generics.Eot as Eot
    
    data L = forall a. Eq a => L Eot.Datatype a 
    
    mkL :: forall a. (Generic a, Eot.HasEot a, Eq a) => a -> L
    mkL = L (Eot.datatype (Proxy @a))

That is, instead of using Typeable and its nominal equality check in order to decide whether two types are equal, use some generic library (here I have used [generics-eot](http://generics-eot.readthedocs.io/en/latest/)) to obtain a structural representation of your types, and compare those instead.

**Comment by mvdan** [comment] 2017-05-15 10:07
So if I understand this correctly:

* This is a bug in GHC under the covers (the one linked)
* This can be worked around in user code as per the last comment

Is that all? Can the workaround be included in `hint` somehow in all GHC versions that don't have the bug fixed?

**Comment by gelisam** [comment] 2017-05-15 11:29
According to the comments in that GHC bug, they don't even plan to fix it!

Since the problem is in the Eq instance for TypeRep, I don't see how you could fix it in `hint`. I guess you could provide a custom `eqTypeRep` function and explain in the documentation why users should use it instead of `(==)`, but you can't change the behavior of `(==)` without creating a newtype, and you can't force your users to use that newtype instead of TypeRep any more that you can force them to use your `eqTypeRep` instead of `(==)`.

**Comment by gelisam** [comment] 2017-05-15 11:33
Oh! Maybe you could generate a new file name each time a module is loaded, so that the first time the fully-qualified name would be `Test1234.T` and the second time it would be `Test1235.T`? `hint` is already generating random module names for other reasons, I think.

**Comment by mvdan** [comment] 2017-05-15 11:50
We could also add some random base64 chars at the end of the filenames, like `Test-a54d833f`. As long as this doesn't break any user code, it sounds like a fine workaround to me. That sounds a little saner to me than keeping an internal counter.

If GHC ever fixes this, we could just remove the filename transformation on those newer versions.

**Comment by cdupont** [comment] 2017-05-15 14:09
@gelisam Yes, using a library for structural equality seems a solution.
I reproduced you example, it works. Regarding Nomyx, the players will need to add a clause to derive Generics, but that doesn't seem too much.

Regarding generating a new filename each time a module is loaded, it doesn't seem to be a good idea (at least for Nomyx). The rules need to communicate with each others, and defining new datatype is part of the game. See for example this rule declarations: http://www.nomyx.net:8000/Nomyx/menu/rules/%20Foundation%20-%20Second%20Republic?ruleNumber=22&decl=Nomyx/Library/Planets.hs

**Comment by cdupont** [comment] 2017-05-16 18:50
So all in all, I don't think Hint makes anything wrong.
GHC is making a false promise on the safety of `cast`, but this as no impact in traditional scenarios: in normal conditions files are compiled all at once so you have one type == one name. However with Hint we introduce a bit more flexibility and this does not hold anymore.

@gelisam do you know any other library that makes structural equality?

**Comment by gelisam** [comment] 2017-05-17 12:18
If you're worried about dependencies, you can probably build something up using Data.Data in base.

**Comment by mvdan** [comment] 2017-05-17 13:27
I understand there is nothing to do to in Hint right now, then. I'm closing the issue. If that changes or if any of you have a patch, please let me know.

@gelisam since you know more Haskell/GHC than I do, I've added you as a member. You should now be able to manage issues and PRs if you wish.

**Closed by mvdan** 2017-05-17 13:27 UTC
