### ISSUE TITLE
7x faster invocation in OSX vs Ubuntu

### ISSUE THREAD

**Issue by fabricatedmath** [mvdan/hint#56] opened 2018-03-03 05:45 UTC
I did
```Haskell
main :: IO ()
main =
  do
    r <- runInterpreter $ do
      setImports ["Prelude"]
      interpret "1+2" (as :: Int)
    print r
```
on my laptop running OSX and it ran in 0.32s
and on my desktop running Ubuntu 16.04 and it ran in 2.21s
both on lts-10.7 with default stack/package yaml (barring hint)

Any ideas on why this might be the case? My laptop is way underpowered compared to my desktop.

**Comment by mvdan** [comment] 2018-03-03 10:11
Are they running the same GHC and Hint versions?

**Comment by fabricatedmath** [comment] 2018-03-03 13:51
Yeah, ghc-8.2.2 and hint-0.7.0 off of
https://www.stackage.org/lts-10.7

**Comment by gelisam** [comment] 2018-03-03 13:54
Does `echo '1+2' | ghci` exhibit the same difference in performance?

**Comment by mvdan** [comment] 2018-03-03 14:32
So, Hint is faster on Mac, but ghci was faster on Linux?

Did you run the commands many times? Maybe there is caching involved, such as having to load GHC stuff from disk on the first run.

**Comment by fabricatedmath** [comment] 2018-03-03 14:34
Yeah, ran many times, very little variability on both

**Comment by gelisam** [comment] 2018-03-03 14:57
> Any ideas on why this might be the case?

The code which loads libraries is OS-specific, so the fact that they don't run at exactly the same speed is not surprising. Hint delegates to the GHC library, which in turn delegates to the OS. So the difference could either be in hint (there's a bit of OS-dependent code, but it's not the loading), in GHC, or in the OS. So the first step is to figure out whether this bug is filed in the right bug tracker :)

> So, Hint is faster on Mac, but ghci was faster on Linux?

If so, this suggests that the problem must indeed be in hint, not GHC!

**Comment by mvdan** [comment] 2018-03-03 14:58
For the record, I've found great variation in build times depending on the GHC version and how each GHC was built. For example, see: https://travis-ci.org/mvdan/hint/builds/334673370

7.10 to 8.0 makes the build+test time jump from 10m to 13m.

And the 7.8 to 7.10 jump had a similar leap downard in performance: https://travis-ci.org/mvdan/hint/builds/236686291

So perhaps the GHCs in Mac and Linux were built differently. Have you tried using binaries from GHC upstream directly? It's more likely that the builds there will be consistent across platforms, as opposed to Homebrew versus Debian or whatever other package manager or distribution.

**Comment by fabricatedmath** [comment] 2018-03-03 15:07
Oh wow, that's it, tried ghc 8.0.2 from lts-9.21 and on Ubuntu it's at 0.28s now, guess ghc-8.2.2 was a major regression.

**Comment by mvdan** [comment] 2018-03-03 15:11
Also, times on my Arch Linux laptop with 8.2.2:

```
$ time echo '1+2' | ghci
real    0m0.159s
user    0m0.125s
sys     0m0.033s
$ time runghc f.hs
real    0m0.302s
user    0m0.266s
sys     0m0.033s
```

So, at least on my Linux setup, both are reasonably fast.

**Comment by fabricatedmath** [comment] 2018-03-03 15:15
And a follow up, so on 8.0.2 vs 8.2.2 with ghci vs hint and OSX vs Ubuntu,  the only one that has an unexpectedly long invocation time is 8.2.2, hint, ubuntu

**Comment by gelisam** [comment] 2018-03-03 19:07
> Are you getting something similar?

Yes, I see the same results. I installed Docker For Mac so I could run the linux and macOS versions of hint and ghc-8.2.2 on the same machine. My results are as follows.

1.  `echo '1+2' | stack exec ghci`
    1. macOS: 0.53s
    2. Linux: 0.69s
2.  `stack exec -- hint-test`
    1. macOS: 0.55s
    2. Linux: 4.8s

What could possibly be causing this? `hint` has a few `#if __GLASGOW_HASKELL__ >= 800` and `#if __GLASGOW_HASKELL__ < 802` checks, but nothing which compares with 822. If has a few `#if defined(mingw32_HOST_OS)` checks, but no checks against `darwin_HOST_OS` nor `linux_HOST_OS`. So the difference must be in one of hint's dependencies.

The most likely dependency is ghc, but if that was the case, the ghci test should have exhibited the same problems. Perhaps the hint test is exercising a part of the ghc library which the ghci test isn't?

**Comment by mvdan** [comment] 2018-03-03 19:10
@gelisam your GHC 8.2 setup on Linux might be different than mine. Have you tried using an Arch docker image, installing `ghc`, and seeing if Hint is still slow?

Note that they use dynamic builds of haskell packages: https://wiki.archlinux.org/index.php/haskell#Problems_with_linking

**Comment by gelisam** [comment] 2018-03-03 20:38
No, I have used the docker image generated by stack.

I have now obtained an image of archlinux, but being unfamiliar with that OS, I only managed to install `ghc` and `cabal-install`, but I could not figure out how to install `hint`. I get errors like "There are files missing in the ‘base-4.10.1.0’ package" and "There are files missing in the ‘directory-1.3.0.2’ package", as if the installation folder was corrupted somehow.

However, I noticed that it isn't just the Linux version which is different, it is also the way in which we run the program. You have used `runghc`, which even on my non-archlinux version of linux (no idea which version of linux stack uses), runs fine:

1. `time runghc src/main.hs`: 0.52s
2. `stack build && time stack exec -- hint-test`: 4.6s
3. `cabal install && time ./dist/build/hint-test/hint-test`: 4.3s

So I am suspecting that the part of the ghc library which the ghci test isn't exercising might be the interaction between the interpreted `1+2` and the compiled `print`? I think `ghci` and `runghc` might both use the interpreted version of `print`, whereas `stack` and `cabal` will produce an executable which will use the compiled version.

**Comment by mvdan** [comment] 2018-03-03 20:53
> as if the installation folder was corrupted somehow.

It's the dynamic haskell libraries stuff - see the arch wiki link I posted above. I've been confused by those errors a dozen times by now.

I also can't reproduce your slowness of the compiled binary:

```
$ time runghc src/Main.hs
Right 3

real    0m0.316s
user    0m0.263s
sys     0m0.051s
$ time dist/build/hint-test/hint-test
Right 3

real    0m0.126s
user    0m0.096s
sys     0m0.029s
```

This is on a very simple hint-test module with just that main file and hint as a build dependency.

**Comment by mvdan** [comment] 2018-03-03 20:58
Also note that, as said before, my system builds dynamic binaries by default:

```
$ ls -lah dist/build/hint-test/hint-test
-rwxr-xr-x 1 mvdan mvdan 42K Mar  3 20:51 dist/build/hint-test/hint-test*
```

The `ldd` output is monstruous:

```
	linux-vdso.so.1 (0x00007ffccbb98000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fc5743b5000)
	libHShint-0.7.0-6N9hqrNgIuXKsbJ4SD15g8-ghc8.2.2.so => /home/mvdan/.cabal/lib/x86_64-linux-ghc-8.2.2/libHShint-0.7.0-6N9hqrNgIuXKsbJ4SD15g8-ghc8.2.2.so (0x00007fc57481b000)
	libHSrandom-1.1-LLUGZ7T9DqQ5vN0Jbcd0We-ghc8.2.2.so => /usr/lib/libHSrandom-1.1-LLUGZ7T9DqQ5vN0Jbcd0We-ghc8.2.2.so (0x00007fc5747b6000)
	libHSexceptions-0.8.3-FtqgxeR4VUg9hGcIqYr2bq-ghc8.2.2.so => /usr/lib/libHSexceptions-0.8.3-FtqgxeR4VUg9hGcIqYr2bq-ghc8.2.2.so (0x00007fc574787000)
	libHStransformers-compat-0.5.1.4-EAh8Ccrgitz4vTZtbTPyCM-ghc8.2.2.so => /usr/lib/libHStransformers-compat-0.5.1.4-EAh8Ccrgitz4vTZtbTPyCM-ghc8.2.2.so (0x00007fc57477d000)
	libHSstm-2.4.5.0-7j9Z9j03i0pHiTKIV2qS3x-ghc8.2.2.so => /usr/lib/libHSstm-2.4.5.0-7j9Z9j03i0pHiTKIV2qS3x-ghc8.2.2.so (0x00007fc57475a000)
	libHSmtl-2.2.2-8XubxMJDT8QLsstvlNotkc-ghc8.2.2.so => /usr/lib/libHSmtl-2.2.2-8XubxMJDT8QLsstvlNotkc-ghc8.2.2.so (0x00007fc57437e000)
	libHSghc-paths-0.1.0.9-jtXMj34IrEDKFvgWnrf0G-ghc8.2.2.so => /usr/lib/libHSghc-paths-0.1.0.9-jtXMj34IrEDKFvgWnrf0G-ghc8.2.2.so (0x00007fc574754000)
	libHSghc-8.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/ghc-8.2.2/libHSghc-8.2.2-ghc8.2.2.so (0x00007fc56fbee000)
	libHSterminfo-0.4.1.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/terminfo-0.4.1.0/libHSterminfo-0.4.1.0-ghc8.2.2.so (0x00007fc56fbb0000)
	libHShoopl-3.10.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/hoopl-3.10.2.2/libHShoopl-3.10.2.2-ghc8.2.2.so (0x00007fc56fb0e000)
	libHSghci-8.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/ghci-8.2.2/libHSghci-8.2.2-ghc8.2.2.so (0x00007fc56f8da000)
	libHSghc-boot-8.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/ghc-boot-8.2.2/libHSghc-boot-8.2.2-ghc8.2.2.so (0x00007fc56f850000)
	libHStransformers-0.5.2.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/transformers-0.5.2.0/libHStransformers-0.5.2.0-ghc8.2.2.so (0x00007fc56f745000)
	libHShpc-0.6.0.3-ghc8.2.2.so => /usr/lib/ghc-8.2.2/hpc-0.6.0.3/libHShpc-0.6.0.3-ghc8.2.2.so (0x00007fc56f711000)
	libHStemplate-haskell-2.12.0.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/template-haskell-2.12.0.0/libHStemplate-haskell-2.12.0.0-ghc8.2.2.so (0x00007fc56f3bf000)
	libHSpretty-1.1.3.3-ghc8.2.2.so => /usr/lib/ghc-8.2.2/pretty-1.1.3.3/libHSpretty-1.1.3.3-ghc8.2.2.so (0x00007fc56f34b000)
	libHSghc-boot-th-8.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/ghc-boot-th-8.2.2/libHSghc-boot-th-8.2.2-ghc8.2.2.so (0x00007fc56f30d000)
	libHSbinary-0.8.5.1-ghc8.2.2.so => /usr/lib/ghc-8.2.2/binary-0.8.5.1/libHSbinary-0.8.5.1-ghc8.2.2.so (0x00007fc56f269000)
	libHScontainers-0.5.10.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/containers-0.5.10.2/libHScontainers-0.5.10.2-ghc8.2.2.so (0x00007fc56ef89000)
	libHSprocess-1.6.1.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/process-1.6.1.0/libHSprocess-1.6.1.0-ghc8.2.2.so (0x00007fc56ef4c000)
	libHSdirectory-1.3.0.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/directory-1.3.0.2/libHSdirectory-1.3.0.2-ghc8.2.2.so (0x00007fc56ef01000)
	libHSunix-2.7.2.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/unix-2.7.2.2/libHSunix-2.7.2.2-ghc8.2.2.so (0x00007fc56ee15000)
	libHSbytestring-0.10.8.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/bytestring-0.10.8.2/libHSbytestring-0.10.8.2-ghc8.2.2.so (0x00007fc56ed20000)
	libHSfilepath-1.4.1.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/filepath-1.4.1.2/libHSfilepath-1.4.1.2-ghc8.2.2.so (0x00007fc57472d000)
	libHStime-1.8.0.2-ghc8.2.2.so => /usr/lib/ghc-8.2.2/time-1.8.0.2/libHStime-1.8.0.2-ghc8.2.2.so (0x00007fc56ec22000)
	libHSdeepseq-1.4.3.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/deepseq-1.4.3.0/libHSdeepseq-1.4.3.0-ghc8.2.2.so (0x00007fc56ec08000)
	libHSarray-0.5.2.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/array-0.5.2.0/libHSarray-0.5.2.0-ghc8.2.2.so (0x00007fc56eb82000)
	libHSbase-4.10.1.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/base-4.10.1.0/libHSbase-4.10.1.0-ghc8.2.2.so (0x00007fc56e1b1000)
	libHSinteger-gmp-1.0.1.0-ghc8.2.2.so => /usr/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0-ghc8.2.2.so (0x00007fc56e175000)
	libHSghc-prim-0.5.1.1-ghc8.2.2.so => /usr/lib/ghc-8.2.2/ghc-prim-0.5.1.1/libHSghc-prim-0.5.1.1-ghc8.2.2.so (0x00007fc56dcd5000)
	libHSrts-ghc8.2.2.so => /usr/lib/ghc-8.2.2/rts/libHSrts-ghc8.2.2.so (0x00007fc56dc6e000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fc56da01000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fc56d7f9000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fc56d5f6000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fc56d3f2000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fc56d1d4000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fc56cf41000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007fc56cd38000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fc56c981000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fc574701000)
```

**Comment by gelisam** [comment] 2018-03-03 21:36
> It's the dynamic haskell libraries stuff - see the arch wiki link I posted above.

I did try to run `cabal configure --disable-library-vanilla --enable-shared --enable-executable-dynamic` before `cabal install hint`, and I have now tried to add the corresponding flags in `~/.cabal/config`, but it didn't help.

**Comment by int-e** [comment] 2018-03-26 20:31
There is a dramatic speed difference between dynamic and statically compiled versions of that test program.

    > cat HT.hs
    import Language.Haskell.Interpreter

    main :: IO ()
    main =
     do
        r <- runInterpreter $ do
          setImports ["Prelude"]
          interpret "1+2" (as :: Int)
        print r
    > ghc --make -static HT.hs
    [...]
    > time ./HT
    Right 3

    real    0m0.322s
    user    0m0.258s
    sys     0m0.065s
    > ghc --make -dynamic HT.hs
    [...]
    > time ./HT
    Right 3

    real    0m0.094s
    user    0m0.084s
    sys     0m0.010s

The reason for this, as far as I understand it, is that the dynamic version uses libc's dynamic linker, while the static version uses a custom linker for loading .o files that is built into ghc; the latter is far less optimized. I suspect that the dynamic linker also benefits from some lazy binding which the custom one doesn't have. (This is one of the lessons I learned from running lambdabot.)

**Comment by mvdan** [comment] 2018-04-08 15:12
@int-e thanks for the useful explanation - since we don't have a better theory, and since this appears to be because of GHC's design, I'm going to close this issue for now.

Please feel free to re-open it (or open a new one) if any workaround for this static binary slowness comes up. Or if the explanation above turns out to be wrong.

**Closed by mvdan** 2018-04-08 15:12 UTC

**Comment by shmish111** [comment] 2018-11-26 16:59
We are currently having this problem with nix on nixos using ghc 8.4, not sure what to do at this point, did anyone have a work around?
